# Generated by Django 4.2.10 on 2025-06-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('date', models.DateField(verbose_name='Дата прогноза')),
                ('min_temperature', models.FloatField(verbose_name='Мин температура °C')),
                ('max_temperature', models.FloatField(verbose_name='Мак температура °C')),
            ],
            options={
                'verbose_name': 'Прогноз погоды',
                'verbose_name_plural': 'Прогнозы погоды',
            },
        ),
    ]
