# Generated by Django 4.2.10 on 2025-06-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_inno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecast',
            name='date',
            field=models.CharField(max_length=32, verbose_name='Дата прогноза'),
        ),
    ]
